name: Deploy React Frontend to Render

on:
  push:
    branches:
      - main   # Only deploy when main branch is updated

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install
        

      - name: Build React app
        run: npm run build

      - name: Build Docker image (production)
        run: |
          docker build -t react-frontend:latest -f Dockerfile.prod .

      - name: Login to Render Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.RENDER_DOCKER_USERNAME }}
          password: ${{ secrets.RENDER_DOCKER_PASSWORD }}

      - name: Deploy to Render via API
        env:
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          curl -X POST "https://api.render.com/deploy/srv-${RENDER_SERVICE_ID}" \
          -H "Authorization: Bearer ${RENDER_API_KEY}" \
          -H "Content-Type: application/json"
